window.GALLERY = [
    { href: "https://drive.google.com/file/d/1GmiQW_aQ39y_uQHQ32kfQpydYpzwZyah/view?usp=sharing", alt: "1" },
  { href: "https://drive.google.com/file/d/1odw_T9_WQqHZk4yzQvGn7mY3Qm3T_Dym/view?usp=sharing", alt: "2" },
  { href: "https://drive.google.com/file/d/1u-orPZcgxjARaHl5MoFL_SfCBF_1BHsg/view?usp=sharing", alt: "3" },
  { href: "https://drive.google.com/file/d/1JFmcgU2TFlz8pm_2fsFjkboXdvIOS-9T/view?usp=sharing", alt: "4" },
  { href: "https://drive.google.com/file/d/1oWO2-UR76IhuKJEie7qbPvsLtfDXODrQ/view?usp=sharing", alt: "5" },
  { href: "https://drive.google.com/file/d/11pJE05MckrEHr6ykkgkNJs2HM8oy_DrU/view?usp=sharing", alt: "6" },
  { href: "https://drive.google.com/file/d/1pzOCAUR2I3y0R6oH0ozhKJbzjK6dd3XU/view?usp=sharing", alt: "7" },
  { href: "https://drive.google.com/file/d/1fWdrhJWGLMT7NBT7IFbBkG9o4dijZG3a/view?usp=sharing", alt: "8" },
  { href: "https://drive.google.com/file/d/1c2ireVQCm1okJGjK7fq4644VZMKzNMIO/view?usp=sharing", alt: "9" },
  { href: "https://drive.google.com/file/d/1P1RYzmfaJ0A15HIzs9piylJwA8bh_3Um/view?usp=sharing", alt: "10" },
  { href: "https://drive.google.com/file/d/15vVuXwV0rofyYzvslni0q9YIwQGThcTn/view?usp=drive_link", alt: "11" },
  { href: "https://drive.google.com/file/d/1HJwfT1UcsUTA6CWL3CA-EnZG2VKhILoh/view?usp=drive_link", alt: "12" },
  { href: "https://drive.google.com/file/d/1sWS70JbBEo8rQNw3JajJpbguJCugeIE4/view?usp=drive_link", alt: "13" },
  { href: "https://drive.google.com/file/d/1ANvMjUzETNF5chIRUOvPyEPiBUVb0JvQ/view?usp=drive_link", alt: "14" },
  { href: "https://drive.google.com/file/d/1G_u1-umndfKvjWLyRThRJf9MGRZLvtNh/view?usp=drive_link", alt: "15" },
  { href: "https://drive.google.com/file/d/1rg9qPCEpVUJJilsbseMVFX3KP-BNCvV5/view?usp=drive_link", alt: "16" },
  { href: "https://drive.google.com/file/d/1rAO0Y_Tn7dIOIu2hxisFWdXasUAvlLVH/view?usp=drive_link", alt: "17" },
  { href: "https://drive.google.com/file/d/1Rc6bYo3MqRM3NlVJLGndyqv3PMsvopqh/view?usp=drive_link", alt: "18" },
  { href: "https://drive.google.com/file/d/1GH8EInox2EGW1H7imQy3p7zIv7-O8gQK/view?usp=drive_link", alt: "19" },
  { href: "https://drive.google.com/file/d/19TdivwfGyE8EDzHZPPFj_YGHEUWklLpU/view?usp=drive_link", alt: "20" },
  { href: "https://drive.google.com/file/d/15FExzLFZEGxSZ9IvWbS3mwXdKVDH0fbV/view?usp=drive_link", alt: "21" },
  { href: "https://drive.google.com/file/d/1v_fjabc_LNTJf3ykyIP3bHrTkJex145E/view?usp=drive_link", alt: "22" },
  { href: "https://drive.google.com/file/d/1FnjmLzyZOXCTJKtnZwbL5_LGIVWt1dFp/view?usp=drive_link", alt: "23" },
  //{ href: "", alt: "" },


];